 user  nginx;
 worker_processes  auto;
 error_log  /var/log/nginx/error.log warn;
 pid        /var/run/nginx.pid;
 events {
     worker_connections  1024;
 }
 http {
     include       mime.types;
     default_type  application/octet-stream;
     sendfile        on;
     gzip on;
     gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
     log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                       '$status $body_bytes_sent "$http_referer" '
                       '"$http_user_agent" "$http_x_forwarded_for"';
     access_log  /var/log/nginx/access.log  main;
     error_log  /var/log/nginx/error.log info;
     server {
         listen       80;
         root /usr/share/nginx/html;
         index index.html;

          client_max_body_size 100M;
           client_body_buffer_size 10M;

           client_header_buffer_size 16k;
           large_client_header_buffers 8 64k;

         location /api/ {
             rewrite ^/api/(.*)$ /$1 break;
             proxy_pass https://tandeem.seven-app.org/;
             proxy_http_version 1.1;
             proxy_connect_timeout       6000;
             proxy_send_timeout          6000;
             proxy_read_timeout          6000;
             send_timeout                6000;

             proxy_set_header X-Real-IP $remote_addr;
             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
             proxy_set_header X-Forwarded-Proto $scheme;
         }

         location / {
            send_timeout 10;
            keepalive_timeout  10;
             try_files $uri $uri/ /index.html;
             add_header X-Frame-Options "SAMEORIGIN";
             add_header X-XSS-Protection "1; mode=block";
             add_header X-Content-Type-Options "nosniff";
             add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
             add_header Strict-Transport-Security 'max-age=15768000;';
             add_header Referrer-Policy 'strict-origin';
         }


     }
 }
